SELECT * from ACCOUNTS
--DELETE FROM ACCOUNTS
--DROP TABLE ACCOUNTS

--Create table APP.ACCOUNTS (
--	ACCOUNTID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
--	ACCOUNTNO VARCHAR(11) NOT NULL,
--	ACCOUNTNAME VARCHAR(48) NOT NULL,
--	UNIQUE (ACCOUNTID)
--)